### ISSUE TITLE
GUI crashes when fitting data loaded from RV Bank

### ISSUE THREAD

**Issue by schaubia** [3fon3fonov/exostriker#102]
Hi,
I've pulled the latest 0.70 version of the tool. When trying to fit data that was loaded directly from the RVBank data base, I ran into the following error causing the program to crash:

Traceback (most recent call last):
  File "/home/Schaubia/Exostriker/exostriker_newapril22/exostriker/exostriker/gui.py", line 7319, in worker_RV_fitting_complete
    self.save_last_session("autosave/auto_save.ses")
  File "/home/Schaubia/Exostriker/exostriker_newapril22/exostriker/exostriker/gui.py", line 8216, in save_last_session
    dill.dump(fit, file_pi) #,protocol=2
  File "/home/Schaubia/anaconda3/lib/python3.7/site-packages/dill/_dill.py", line 276, in dump
    Pickler(file, protocol, **_kwds).dump(obj)
  File "/home/Schaubia/anaconda3/lib/python3.7/site-packages/dill/_dill.py", line 498, in dump
    StockPickler.dump(self, obj)
  File "/home/Schaubia/anaconda3/lib/python3.7/pickle.py", line 437, in dump
    self.save(obj)
  File "/home/Schaubia/anaconda3/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/home/Schaubia/anaconda3/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/home/Schaubia/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/Schaubia/anaconda3/lib/python3.7/site-packages/dill/_dill.py", line 990, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/home/Schaubia/anaconda3/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/home/Schaubia/anaconda3/lib/python3.7/pickle.py", line 882, in _batch_setitems
    save(v)
  File "/home/Schaubia/anaconda3/lib/python3.7/pickle.py", line 524, in save
    rv = reduce(self.proto)
TypeError: can't pickle PlotWidget objects

Aborted (core dumped)

**Comment by 3fon3fonov** [comment]
Confirmed and fixed! I had forgotten a test code inside, but now should work fine. Please check.

**Comment by schaubia** [comment]
It's working fine now. Thanks!
