### ISSUE TITLE
Problem with gfortran on Mac OS 14.2.1

### ISSUE THREAD

**Issue by Matt-Standing** [3fon3fonov/exostriker#127]
Hi there,

I'm experiencing a similar issue to that in issue #112 

When running the python script for the gui I get the following output:

_New source code available: Updating Keplerian Simplex
New source code available: Updating Keplerian L-M
New source code available: Updating N-body Simplex
New source code available: Updating N-body L-M
New source code available: Updating Mixed Simplex

Something went wrong!!! 

Perhaps you do not have user permission to compile code in the Exo-Striker directory?
Or perhaps, you do not have 'gfortran' installed? 

Trying 

$ gfortran -v 

returned:

[['gfortran:', 'warning:', 'could', 'not', 'understand', 'version', '14.01.00']_

The gui then crashes as soon as I try loading any RV datasets.

I've tried following the steps in several places and those you outlined in #112 and running sudo exostriker gives the same warning so I don't believe it's a permissions problem. 
Running  bash install_f77_opt.sh gives:

_gfortran: warning: could not understand version 14.01.00
ld: -rpath can only be used when targeting Mac OS X 10.5 or later
collect2: error: ld returned 1 exit status
gfortran: warning: could not understand version 14.01.00
ld: -rpath can only be used when targeting Mac OS X 10.5 or later
collect2: error: ld returned 1 exit status
gfortran: warning: could not understand version 14.01.00
ld: -rpath can only be used when targeting Mac OS X 10.5 or later
collect2: error: ld returned 1 exit status
gfortran: warning: could not understand version 14.01.00
ld: -rpath can only be used when targeting Mac OS X 10.5 or later
collect2: error: ld returned 1 exit status
gfortran: warning: could not understand version 14.01.00
ld: -rpath can only be used when targeting Mac OS X 10.5 or later
collect2: error: ld returned 1 exit status_

conda list shows my gfortran versions:
gfortran                  11.3.0               h1a9baa2_0  
gfortran_impl_osx-64      11.3.0              h29cdc64_28  
gfortran_osx-64           11.3.0               h96634ac_0  

Searching the could not understand version problem everyone just suggests updating gcc, but my gcc is up to date. I'm using a machine with the new M3 chip Sonoma 14.2.1, could this be the issue?

If not any ideas would be greatly appreciated, thank you.

**Comment by 3fon3fonov** [comment]
@Matt-Standing, First you seems to use an old ExoStriker! The output you list would be printed by versions < 0.84, but after 0.85 there was a major upgrade in the code. The Current version is 0.86, please git pull the new version.

This of course might not fully resolve your problem since you are using anaconda. Do:

$ conda deactivate 

Then follow the installation procedure in the repo for Mac OS. 

Anaconda and gfortran somehow do not work on Mac OS, no idea why.

**Comment by Matt-Standing** [comment]
Ah yes I forgot I was on the exostriker-ready branch, I used that one since the file names stated in the installation pages were missing/different from the main branch.

I switched to the main branch and followed the install procedure again to replace v.0.84 its now on 0.85. Now the error reads:
ValueError: A valid Fortran version was not found in this string:
x86_64-apple-darwin13.4.0-gfortran: warning: could not understand version 14.01.00

Is there a way of getting it to work in the conda environ? I'm a little reluctant to install in my base environ at risk of breaking everything else.

I tried deactivating and running bash install_f77_opt.sh (which ran with no issues) and then going back into the environ but no luck, I guess it needs to be done in the same environ, which makes sense.

**Comment by Matt-Standing** [comment]
Hi @3fon3fonov thanks for the help, I managed to move my other code and have now tried installing out of anaconda.

I did pip3 install git+https://github.com/3fon3fonov/exostriker which went fine, but when running exostriker I get:

Traceback (most recent call last):
  File "/usr/local/bin/exostriker", line 5, in <module>
    from exostriker.gui import main
  File "/usr/local/lib/python3.11/site-packages/exostriker/__init__.py", line 1, in <module>
    from exostriker import gui
  File "/usr/local/lib/python3.11/site-packages/exostriker/gui.py", line 50, in <module>
    import RV_mod as rv
  File "/usr/local/lib/python3.11/site-packages/exostriker/lib/RV_mod/__init__.py", line 108, in <module>
    from .rvmod import *
  File "/usr/local/lib/python3.11/site-packages/exostriker/lib/RV_mod/rvmod/__init__.py", line 762, in <module>
    from . import rvmod_for
ImportError: dlopen(/usr/local/lib/python3.11/site-packages/exostriker/lib/RV_mod/rvmod/rvmod_for.cpython-311-darwin.so, 0x0002): tried: '/usr/local/lib/python3.11/site-packages/exostriker/lib/RV_mod/rvmod/rvmod_for.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/python3.11/site-packages/exostriker/lib/RV_mod/rvmod/rvmod_for.cpython-311-darwin.so' (no such file), '/usr/local/lib/python3.11/site-packages/exostriker/lib/RV_mod/rvmod/rvmod_for.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))

Abort trap: 6

I also tried following your steps from #126 by removing .so files just in case but I still get the same error running "exostriker"

Any ideas?

Thanks,
Matt

**Comment by 3fon3fonov** [comment]
@Matt-Standing, since I have no idea where is the problem, I can offer we chat over Zoom and debug. It could be something more general where I have to invest time, or something simple intrinsic to your Mac OS installation/Python/gfortran.

Write me on 3fon3fonov_at_gmail.com

**Comment by 3fon3fonov** [comment]
I am closing due to inactivity.
