### ISSUE TITLE
PyQt6 error: metadata-generation-failed on Ubuntu

### ISSUE THREAD

**Issue by Astrocyy** [3fon3fonov/exostriker#134]
Dear Trifon,

I am installing the latest version of exostriker on Ubuntu 18.04.6 LTS. Before the installation of ES, I first installed the latest version of Anaconda_liunx successfully and the version of Python is 3.12. Then I started to "pip install exostriker", however, these errors about PyQt6 keep showing up, so the installation failed.

> Collecting formlayout==1.2.0 (from exostriker==0.90.1)
>   Using cached formlayout-1.2.0-py2.py3-none-any.whl.metadata (2.1 kB)
> Collecting PyQt6 (from exostriker==0.90.1)
>   Using cached PyQt6-6.7.1.tar.gz (1.1 MB)
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... done
>   Preparing metadata (pyproject.toml) ... error
>   error: subprocess-exited-with-error
>   
>   × Preparing metadata (pyproject.toml) did not run successfully.
>   │ exit code: 1
>   ╰─> [20 lines of output]
>       Querying qmake about your Qt installation...
>       Traceback (most recent call last):
>         File "/home/yingyicao/anaconda3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
>           main()
>         File "/home/yingyicao/anaconda3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
>           json_out['return_val'] = hook(**hook_input['kwargs'])
>                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "/home/yingyicao/anaconda3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
>           whl_basename = backend.build_wheel(metadata_directory, config_settings)
>                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "/tmp/pip-build-env-85nraraq/overlay/lib/python3.12/site-packages/sipbuild/api.py", line 28, in build_wheel
>           project = AbstractProject.bootstrap('wheel',
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "/tmp/pip-build-env-85nraraq/overlay/lib/python3.12/site-packages/sipbuild/abstract_project.py", line 74, in bootstrap
>           project.setup(pyproject, tool, tool_description)
>         File "/tmp/pip-build-env-85nraraq/overlay/lib/python3.12/site-packages/sipbuild/project.py", line 624, in setup
>           self.update(tool)
>         File "/tmp/pip-install-dzsri4qk/pyqt6_8678b55506ab484da8c59eb853dd44a2/project.py", line 163, in update
>           raise UserException(
>       sipbuild.exceptions.UserException
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: metadata-generation-failed
> 
> × Encountered error while generating package metadata.
> ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip.
> hint: See above for details.

I also tried Python 3.10 and 3.11(all based on Anaconda), these errors still exist. I wonder if it is the problem of Anaconda...
I would greatly appreciate your assistance in answering this question.
Thanks!

**Comment by 3fon3fonov** [comment]
The problem is always in anaconda. 

Try:

$python3.12 -m pip install PyQt6

and report if you manage to install it.
