### ISSUE TITLE
python es_guy.py does nothing OS X

### ISSUE THREAD

**Issue by jvines** [3fon3fonov/exostriker#37]
Exactly what the title says. I followed installation instructions but when I run es_gui, nothing happens

**Comment by 3fon3fonov** [comment]
I cannot see the same. Just tried it on three different Mac OS X. There must be an error in the terminal. 

try :

python es_gui.py -debug


and post the output.

**Comment by jvines** [comment]
Hi @3fon3fonov , thanks for the quick answer.

I cloned the repo today, and this is the terminal output of `python es_gui.py -debug`

```
New source code available: Updating Keplerian Simplex
New source code available: Updating Keplerian L-M
New source code available: Updating N-body Simplex
New source code available: Updating  N-body L-M
New source code available: Updating Mixed Simplex
===== 2019.11.16 00:11:47 =====
Traceback (most recent call last):
  File "es_gui.py", line 6386, in <module>
    main()
  File "es_gui.py", line 6370, in main
    window = Exo_striker()
  File "es_gui.py", line 6338, in __init__
    self.check_fortran_routines()
  File "es_gui.py", line 5649, in check_fortran_routines
    r1 = float(result1[0][0])
IndexError: list index out of range
```

**Comment by jvines** [comment]
Also, that error occurs even after a clean clone or git pull

**Comment by 3fon3fonov** [comment]
Currently, "The Exo Striker" needs a number of Fortran routines to work properly and these must be compiled on the User side. It looks like your Fortran routines are not compiled correctly, or are not compiled at all!  Have you run the bash script for Mac OS in the ./installer directory? If not, you must, if Yes, then I would be interested in what is the output of your gfortran, and/or your gfortran version.

In the root directory of the tool do the following:

bash installers/bash installers/MAC_OS_install.sh


if you have anaconda you may try (not recommended if you already made a system install):

bash installers/anaconda_install.sh


either way, you must get "Yes" to all packages, and then you are asked if you want to compile the swift library. Select Yes (i.e. #1). Then once the library is compiled you can now compile the Fortran
routines used for fitting and the N-body integrators. 


Let me know what is the outcome of the bash script installer.

**Comment by 3fon3fonov** [comment]
@jvines any progress? Meanwhile, many more people were able to install the tool on MAC OS, so I would be interested if you solved the problem following the standard instructions or there was a true bug.

**Comment by 3fon3fonov** [comment]
I am closing since I am sure the tool works on MAC OS. @jvines if you still have problems you are welcome to provide more info and reopen this issue.

**Comment by jvines** [comment]
Hi @3fon3fonov , sorry for taking so long.

I think the problem might be that the installation routine isn't compiling the required FORTRAN routines.

**Comment by jvines** [comment]
This is the output I get from bash installers/anaconda_install.sh
```
For which anaconda version we want to check/install packages?
gfortran - yes!
csh - yes!
rxvt - not installed! Please install the rxvt bash shell for better experience (xterm used by default)
PyQt5 - yes!
numpy - yes!
scipy - yes!
matplotlib - yes!
qtconsole - yes!
jupyter - yes!
pathos - yes!
dill - yes!
emcee - yes!
corner - yes!
celerite - yes!
dynesty - yes!
batman - yes!
 
 
Installing the swift N-body lib, OK?  (you must, if you haven't done it already!)
 
 
DIRECTORY: anal
No need to precompile
Doing Fortran
[1] 4889
anal_energy
a - anal_energy.o
[2] 4898
anal_energy_write
a - anal_energy_write.o
[3] 4907
anal_jacobi
a - anal_jacobi.o
[4] 4916
anal_jacobi_write
a - anal_jacobi_write.o
Done directory /Users/jvines/github/trifon/source/swift_j/anal
DIRECTORY: bs
No need to precompile
Doing Fortran
[1] 4933
bs_der
a - bs_der.o
[2] 4942
bs_der_pl
a - bs_der_pl.o
[3] 4951
bs_int
a - bs_int.o
[4] 4960
bs_int_pl
a - bs_int_pl.o
[5] 4980
bs_step
a - bs_step.o
Done directory /Users/jvines/github/trifon/source/swift_j/bs
DIRECTORY: coord
No need to precompile
Doing Fortran
[1] 5006
coord_b2h
a - coord_b2h.o
[2] 5015
coord_b2h_tp
a - coord_b2h_tp.o
[3] 5024
coord_b2j
a - coord_b2j.o
[4] 5038
coord_h2b
a - coord_h2b.o
[5] 5063
coord_h2b_tp
a - coord_h2b_tp.o
[6] 5072
coord_h2j
a - coord_h2j.o
[7] 5081
coord_j2b
a - coord_j2b.o
[8] 5090
coord_j2h
a - coord_j2h.o
[9] 5099
coord_vb2h
a - coord_vb2h.o
[10] 5108
coord_vb2h_tp
a - coord_vb2h_tp.o
[11] 5117
coord_vh2b
a - coord_vh2b.o
[12] 5126
coord_vh2b_tp
a - coord_vh2b_tp.o
[13] 5135
coord_vh2vj
a - coord_vh2vj.o
Done directory /Users/jvines/github/trifon/source/swift_j/coord
DIRECTORY: discard
No need to precompile
Doing Fortran
[1] 5152
discard
a - discard.o
[2] 5161
discard_mass_merge
a - discard_mass_merge.o
[3] 5170
discard_mass_merge5
a - discard_mass_merge5.o
[4] 5179
discard_mass_peri
a - discard_mass_peri.o
[5] 5188
discard_mass_reorder
a - discard_mass_reorder.o
[6] 5197
discard_mass_reorder5
a - discard_mass_reorder5.o
[7] 5206
discard_massive
a - discard_massive.o
[8] 5215
discard_massive5
a - discard_massive5.o
[9] 5224
discard_peri
a - discard_peri.o
[10] 5233
discard_pl
a - discard_pl.o
[11] 5242
discard_pl_close
a - discard_pl_close.o
[12] 5263
discard_sun
a - discard_sun.o
Done directory /Users/jvines/github/trifon/source/swift_j/discard
DIRECTORY: io
Doing precompiler
[1] 5288
/usr/bin/cpp -D_OPEN_POSITION -D_RECUR_SUB io_open.F io_open_CPP.f
Doing Fortran
[2] 5293
io_discard_mass
a - io_discard_mass.o
[3] 5302
io_discard_merge
a - io_discard_merge.o
[4] 5311
io_discard_write
a - io_discard_write.o
[5] 5336
io_dump_param
a - io_dump_param.o
[6] 5350
io_dump_pl
a - io_dump_pl.o
[7] 5359
io_dump_pl_symba
a - io_dump_pl_symba.o
[8] 5368
io_dump_tp
a - io_dump_tp.o
[9] 5377
io_energy_write
a - io_energy_write.o
[10] 5386
io_getns
a - io_getns.o
[11] 5399
io_init_param
a - io_init_param.o
[12] 5408
io_init_pl
a - io_init_pl.o
[13] 5417
io_init_pl_symba
a - io_init_pl_symba.o
[14] 5426
io_init_tp
a - io_init_tp.o
[15] 5435
io_jacobi_write
a - io_jacobi_write.o
[16] 5444
io_lyap2_write
a - io_lyap2_write.o
[17] 5453
io_lyap_init
a - io_lyap_init.o
[18] 5462
io_lyap_write
a - io_lyap_write.o
[19] 5471
io_mvits_init
a - io_mvits_init.o
[20] 5480
io_open_CPP
a - io_open_CPP.o
[21] 5489
io_read_hdr
a - io_read_hdr.o
[22] 5498
io_read_hdr_r
a - io_read_hdr_r.o
[23] 5507
io_read_line
a - io_read_line.o
[24] 5516
io_read_line_r
a - io_read_line_r.o
[25] 5525
io_read_mass
a - io_read_mass.o
[26] 5554
io_splitname
a - io_splitname.o
[27] 5563
io_write_frame
a - io_write_frame.o
[28] 5572
io_write_frame_r
a - io_write_frame_r.o
[29] 5581
io_write_hdr
a - io_write_hdr.o
[30] 5592
io_write_hdr_r
a - io_write_hdr_r.o
[31] 5620
io_write_line
a - io_write_line.o
[32] 5629
io_write_line_r
a - io_write_line_r.o
[33] 5638
io_write_mass
a - io_write_mass.o
Done directory /Users/jvines/github/trifon/source/swift_j/io
DIRECTORY: lyap
No need to precompile
Doing Fortran
[1] 5655
lyap_renorm
a - lyap_renorm.o
[2] 5664
lyap_step
a - lyap_step.o
[3] 5673
lyap_step_sh
a - lyap_step_sh.o
Done directory /Users/jvines/github/trifon/source/swift_j/lyap
DIRECTORY: lyap2
No need to precompile
Doing Fortran
[1] 5690
lyap2_acc_tp
a - lyap2_acc_tp.o
[2] 5699
lyap2_drift_dan
a - lyap2_drift_dan.o
[3] 5708
lyap2_drift_kepu
a - lyap2_drift_kepu.o
[4] 5717
lyap2_drift_one
a - lyap2_drift_one.o
[5] 5726
lyap2_drift_tp
a - lyap2_drift_tp.o
[6] 5735
lyap2_kepu_mikk
a - lyap2_kepu_mikk.o
[7] 5744
lyap2_step
a - lyap2_step.o
[8] 5753
lyap2_step_tp
a - lyap2_step_tp.o
Done directory /Users/jvines/github/trifon/source/swift_j/lyap2
DIRECTORY: mvits
No need to precompile
Doing Fortran
[1] 5770
mvits_getacch_tp
a - mvits_getacch_tp.o
[2] 5779
mvits_init_rot
a - mvits_init_rot.o
[3] 5788
mvits_kickvh_tp
a - mvits_kickvh_tp.o
[4] 5797
mvits_lstep_tp
a - mvits_lstep_tp.o
[5] 5806
mvits_obl_kick
a - mvits_obl_kick.o
[6] 5815
mvits_rotate
a - mvits_rotate.o
[7] 5835
mvits_rstep_tp
a - mvits_rstep_tp.o
[8] 5853
mvits_step
a - mvits_step.o
Done directory /Users/jvines/github/trifon/source/swift_j/mvits
DIRECTORY: mvs/drift
No need to precompile
Doing Fortran
[1] 5870
drift
a - drift.o
[2] 5879
drift_dan
a - drift_dan.o
[3] 5900
drift_kepmd
a - drift_kepmd.o
[4] 5918
drift_kepu
a - drift_kepu.o
[5] 5927
drift_kepu_fchk
a - drift_kepu_fchk.o
[6] 5936
drift_kepu_guess
a - drift_kepu_guess.o
[7] 5945
drift_kepu_lag
a - drift_kepu_lag.o
[8] 5954
drift_kepu_new
a - drift_kepu_new.o
[9] 5963
drift_kepu_p3solve
a - drift_kepu_p3solve.o
[10] 5972
drift_kepu_stumpff
a - drift_kepu_stumpff.o
[11] 5981
drift_one
a - drift_one.o
[12] 5990
drift_tp
a - drift_tp.o
Done directory /Users/jvines/github/trifon/source/swift_j/mvs/drift
DIRECTORY: mvs/getacch
No need to precompile
Doing Fortran
[1] 6007
getacch
a - getacch.o
[2] 6016
getacch_ah0
a - getacch_ah0.o
[3] 6025
getacch_ah1
a - getacch_ah1.o
[4] 6034
getacch_ah2
a - getacch_ah2.o
[5] 6043
getacch_ah3
a - getacch_ah3.o
[6] 6052
getacch_ah3_tp
a - getacch_ah3_tp.o
[7] 6061
getacch_ir3
a - getacch_ir3.o
[8] 6070
getacch_tp
a - getacch_tp.o
Done directory /Users/jvines/github/trifon/source/swift_j/mvs/getacch
DIRECTORY: mvs/kickvh
No need to precompile
Doing Fortran
[1] 6087
kickvh
a - kickvh.o
[2] 6096
kickvh_tp
a - kickvh_tp.o
Done directory /Users/jvines/github/trifon/source/swift_j/mvs/kickvh
DIRECTORY: mvs/step
No need to precompile
Doing Fortran
[1] 6113
step_dkd
a - step_dkd.o
[2] 6139
step_dkd_pl
a - step_dkd_pl.o
[3] 6151
step_dkd_tp
a - step_dkd_tp.o
[4] 6160
step_kdk
a - step_kdk.o
[5] 6169
step_kdk_pl
a - step_kdk_pl.o
[6] 6182
step_kdk_tp
a - step_kdk_tp.o
Done directory /Users/jvines/github/trifon/source/swift_j/mvs/step
DIRECTORY: orbel
No need to precompile
Doing Fortran
[1] 6216
orbel_eget
a - orbel_eget.o
[2] 6225
orbel_ehie
a - orbel_ehie.o
[3] 6234
orbel_ehybrid
a - orbel_ehybrid.o
[4] 6243
orbel_el2xv
a - orbel_el2xv.o
[5] 6252
orbel_esolmd
a - orbel_esolmd.o
[6] 6261
orbel_fget
a - orbel_fget.o
[7] 6270
orbel_fhybrid
a - orbel_fhybrid.o
[8] 6279
orbel_flon
a - orbel_flon.o
[9] 6288
orbel_scget
a - orbel_scget.o
[10] 6297
orbel_schget
a - orbel_schget.o
[11] 6306
orbel_xv2aeq
a - orbel_xv2aeq.o
[12] 6315
orbel_xv2el
a - orbel_xv2el.o
[13] 6324
orbel_zget
a - orbel_zget.o
Done directory /Users/jvines/github/trifon/source/swift_j/orbel
DIRECTORY: rmvs
No need to precompile
Doing Fortran
[1] 6341
rmvs_chk
a - rmvs_chk.o
[2] 6350
rmvs_chk_ind
a - rmvs_chk_ind.o
[3] 6359
rmvs_elog
a - rmvs_elog.o
[4] 6368
rmvs_obl_acc
a - rmvs_obl_acc.o
[5] 6377
rmvs_peri
a - rmvs_peri.o
[6] 6386
rmvs_step
a - rmvs_step.o
[7] 6395
rmvs_step_in
a - rmvs_step_in.o
[8] 6424
rmvs_step_in_mvpl
a - rmvs_step_in_mvpl.o
[9] 6433
rmvs_step_in_tp
a - rmvs_step_in_tp.o
[10] 6442
rmvs_step_out
a - rmvs_step_out.o
Done directory /Users/jvines/github/trifon/source/swift_j/rmvs
DIRECTORY: rmvs2
No need to precompile
Doing Fortran
[1] 6467
rmvs2_interp
a - rmvs2_interp.o
[2] 6489
rmvs2_interp_o
a - rmvs2_interp_o.o
[3] 6498
rmvs2_step
a - rmvs2_step.o
[4] 6507
rmvs2_step_out
a - rmvs2_step_out.o
Done directory /Users/jvines/github/trifon/source/swift_j/rmvs2
DIRECTORY: rmvs3
No need to precompile
Doing Fortran
[1] 6524
rmvs3_chk
a - rmvs3_chk.o
[2] 6533
rmvs3_elog
a - rmvs3_elog.o
[3] 6542
rmvs3_interp
a - rmvs3_interp.o
[4] 6551
rmvs3_step
a - rmvs3_step.o
[5] 6565
rmvs3_step_in
a - rmvs3_step_in.o
[6] 6574
rmvs3_step_out
a - rmvs3_step_out.o
[7] 6583
rmvs3_step_out2
a - rmvs3_step_out2.o
Done directory /Users/jvines/github/trifon/source/swift_j/rmvs3
DIRECTORY: tu4
No need to precompile
Doing Fortran
[1] 6600
tu4_getaccb
a - tu4_getaccb.o
[2] 6609
tu4_getaccb_tp
a - tu4_getaccb_tp.o
[3] 6618
tu4_ldrift
a - tu4_ldrift.o
[4] 6627
tu4_ldrift_tp
a - tu4_ldrift_tp.o
[5] 6636
tu4_step
a - tu4_step.o
[6] 6656
tu4_vkickb
a - tu4_vkickb.o
[7] 6674
tu4_vkickb_tp
a - tu4_vkickb_tp.o
Done directory /Users/jvines/github/trifon/source/swift_j/tu4
DIRECTORY: obl
No need to precompile
Doing Fortran
[1] 6691
obl_acc
a - obl_acc.o
[2] 6700
obl_acc_tp
a - obl_acc_tp.o
[3] 6714
obl_pot
a - obl_pot.o
Done directory /Users/jvines/github/trifon/source/swift_j/obl
DIRECTORY: util
No need to precompile
Doing Fortran
[1] 6747
util_exit
a - util_exit.o
[2] 6756
util_hills
a - util_hills.o
[3] 6765
util_hills1
a - util_hills1.o
[4] 6774
util_mass_peri
a - util_mass_peri.o
[5] 6783
util_peri
a - util_peri.o
[6] 6792
util_version
a - util_version.o
Done directory /Users/jvines/github/trifon/source/swift_j/util
DIRECTORY: helio
No need to precompile
Doing Fortran
[1] 6809
helio_drift
a - helio_drift.o
[2] 6818
helio_getacch
a - helio_getacch.o
[3] 6827
helio_getacch_tp
a - helio_getacch_tp.o
[4] 6836
helio_lindrift
a - helio_lindrift.o
[5] 6845
helio_lindrift_tp
a - helio_lindrift_tp.o
[6] 6854
helio_step
a - helio_step.o
[7] 6863
helio_step_pl
a - helio_step_pl.o
[8] 6872
helio_step_tp
a - helio_step_tp.o
Done directory /Users/jvines/github/trifon/source/swift_j/helio
DIRECTORY: symba3
Doing precompiler
[1] 6889
/usr/bin/cpp -D_OPEN_POSITION -D_RECUR_SUB symba3_step_recur.F symba3_step_recur_CPP.f
Doing Fortran
[2] 6894
symba3_chk
a - symba3_chk.o
[3] 6903
symba3_getacch
a - symba3_getacch.o
[4] 6912
symba3_helio_drift
a - symba3_helio_drift.o
[5] 6921
symba3_helio_getacch
a - symba3_helio_getacch.o
[6] 6934
symba3_kick
a - symba3_kick.o
[7] 6959
symba3_merge
a - symba3_merge.o
[8] 6968
symba3_nbodm
a - symba3_nbodm.o
[9] 6977
symba3_step_helio
a - symba3_step_helio.o
[10] 6986
symba3_step_interp
a - symba3_step_interp.o
[11] 7010
symba3_step_pl
a - symba3_step_pl.o
[12] 7025
symba3_step_recur_CPP
a - symba3_step_recur_CPP.o
Done directory /Users/jvines/github/trifon/source/swift_j/symba3
DIRECTORY: symba4
Doing precompiler
[1] 7042
/usr/bin/cpp -D_OPEN_POSITION -D_RECUR_SUB symba4_step_recur.F symba4_step_recur_CPP.f
Doing Fortran
[2] 7047
symba4_chk
a - symba4_chk.o
[3] 7056
symba4_getacch
a - symba4_getacch.o
[4] 7065
symba4_helio_drift
a - symba4_helio_drift.o
[5] 7074
symba4_helio_getacch
a - symba4_helio_getacch.o
[6] 7083
symba4_kick
a - symba4_kick.o
[7] 7092
symba4_merge
a - symba4_merge.o
[8] 7101
symba4_nbodm
a - symba4_nbodm.o
[9] 7110
symba4_step_helio
a - symba4_step_helio.o
[10] 7119
symba4_step_interp
a - symba4_step_interp.o
[11] 7128
symba4_step_pl
a - symba4_step_pl.o
[12] 7137
symba4_step_recur_CPP
a - symba4_step_recur_CPP.o
Done directory /Users/jvines/github/trifon/source/swift_j/symba4
DIRECTORY: symba5
Doing precompiler
[1] 7154
/usr/bin/cpp -D_OPEN_POSITION -D_RECUR_SUB symba5_step_recur.F symba5_step_recur_CPP.f
Doing Fortran
[2] 7159
symba5_chk
a - symba5_chk.o
[3] 7168
symba5_getacch
a - symba5_getacch.o
[4] 7177
symba5_helio_drift
a - symba5_helio_drift.o
[5] 7186
symba5_helio_getacch
a - symba5_helio_getacch.o
[6] 7215
symba5_kick
a - symba5_kick.o
[7] 7224
symba5_merge
a - symba5_merge.o
[8] 7233
symba5_nbodm
a - symba5_nbodm.o
[9] 7242
symba5_step_helio
a - symba5_step_helio.o
[10] 7266
symba5_step_interp
a - symba5_step_interp.o
[11] 7281
symba5_step_pl
a - symba5_step_pl.o
[12] 7290
symba5_step_recur_CPP
a - symba5_step_recur_CPP.o
Done directory /Users/jvines/github/trifon/source/swift_j/symba5
DIRECTORY: symba5d
No need to precompile
Doing Fortran
[1] 7307
helio_drag
a - helio_drag.o
[2] 7316
symba5d_step_helio
a - symba5d_step_helio.o
[3] 7325
symba5d_step_interp
a - symba5d_step_interp.o
[4] 7334
symba5d_step_pl
a - symba5d_step_pl.o
Done directory /Users/jvines/github/trifon/source/swift_j/symba5d
DIRECTORY: symba5s
Doing precompiler
[1] 7351
/usr/bin/cpp -D_OPEN_POSITION -D_RECUR_SUB symba5s_step_recur.F symba5s_step_recur_CPP.f
Doing Fortran
[2] 7356
io_write_spin
a - io_write_spin.o
[3] 7365
spin_planets
a - spin_planets.o
[4] 7374
spin_planets_enc
a - spin_planets_enc.o
[5] 7383
spin_planets_noenc
a - spin_planets_noenc.o
[6] 7392
spin_sun
a - spin_sun.o
[7] 7401
symba5s_step_helio
a - symba5s_step_helio.o
[8] 7410
symba5s_step_interp
a - symba5s_step_interp.o
[9] 7433
symba5s_step_pl
a - symba5s_step_pl.o
[10] 7448
symba5s_step_recur_CPP
a - symba5s_step_recur_CPP.o
Done directory /Users/jvines/github/trifon/source/swift_j/symba5s
__.SYMDEF SORTED
anal_energy.o
anal_energy_write.o
anal_jacobi.o
anal_jacobi_write.o
bs_der.o
bs_der_pl.o
bs_int.o
bs_int_pl.o
bs_step.o
coord_b2h.o
coord_b2h_tp.o
coord_b2j.o
coord_h2b.o
coord_h2b_tp.o
coord_h2j.o
coord_j2b.o
coord_j2h.o
coord_vb2h.o
coord_vb2h_tp.o
coord_vh2b.o
coord_vh2b_tp.o
coord_vh2vj.o
discard.o
discard_mass_merge.o
discard_mass_merge5.o
discard_mass_peri.o
discard_mass_reorder.o
discard_mass_reorder5.o
discard_massive.o
discard_massive5.o
discard_peri.o
discard_pl.o
discard_pl_close.o
discard_sun.o
io_discard_mass.o
io_discard_merge.o
io_discard_write.o
io_dump_param.o
io_dump_pl.o
io_dump_pl_symba.o
io_dump_tp.o
io_energy_write.o
io_getns.o
io_init_param.o
io_init_pl.o
io_init_pl_symba.o
io_init_tp.o
io_jacobi_write.o
io_lyap2_write.o
io_lyap_init.o
io_lyap_write.o
io_mvits_init.o
io_open_CPP.o
io_read_hdr.o
io_read_hdr_r.o
io_read_line.o
io_read_line_r.o
io_read_mass.o
io_splitname.o
io_write_frame.o
io_write_frame_r.o
io_write_hdr.o
io_write_hdr_r.o
io_write_line.o
io_write_line_r.o
io_write_mass.o
lyap_renorm.o
lyap_step.o
lyap_step_sh.o
lyap2_acc_tp.o
lyap2_drift_dan.o
lyap2_drift_kepu.o
lyap2_drift_one.o
lyap2_drift_tp.o
lyap2_kepu_mikk.o
lyap2_step.o
lyap2_step_tp.o
mvits_getacch_tp.o
mvits_init_rot.o
mvits_kickvh_tp.o
mvits_lstep_tp.o
mvits_obl_kick.o
mvits_rotate.o
mvits_rstep_tp.o
mvits_step.o
drift.o
drift_dan.o
drift_kepmd.o
drift_kepu.o
drift_kepu_fchk.o
drift_kepu_guess.o
drift_kepu_lag.o
drift_kepu_new.o
drift_kepu_p3solve.o
drift_kepu_stumpff.o
drift_one.o
drift_tp.o
getacch.o
getacch_ah0.o
getacch_ah1.o
getacch_ah2.o
getacch_ah3.o
getacch_ah3_tp.o
getacch_ir3.o
getacch_tp.o
kickvh.o
kickvh_tp.o
step_dkd.o
step_dkd_pl.o
step_dkd_tp.o
step_kdk.o
step_kdk_pl.o
step_kdk_tp.o
orbel_eget.o
orbel_ehie.o
orbel_ehybrid.o
orbel_el2xv.o
orbel_esolmd.o
orbel_fget.o
orbel_fhybrid.o
orbel_flon.o
orbel_scget.o
orbel_schget.o
orbel_xv2aeq.o
orbel_xv2el.o
orbel_zget.o
rmvs_chk.o
rmvs_chk_ind.o
rmvs_elog.o
rmvs_obl_acc.o
rmvs_peri.o
rmvs_step.o
rmvs_step_in.o
rmvs_step_in_mvpl.o
rmvs_step_in_tp.o
rmvs_step_out.o
rmvs2_interp.o
rmvs2_interp_o.o
rmvs2_step.o
rmvs2_step_out.o
rmvs3_chk.o
rmvs3_elog.o
rmvs3_interp.o
rmvs3_step.o
rmvs3_step_in.o
rmvs3_step_out.o
rmvs3_step_out2.o
tu4_getaccb.o
tu4_getaccb_tp.o
tu4_ldrift.o
tu4_ldrift_tp.o
tu4_step.o
tu4_vkickb.o
tu4_vkickb_tp.o
obl_acc.o
obl_acc_tp.o
obl_pot.o
util_exit.o
util_hills.o
util_hills1.o
util_mass_peri.o
util_peri.o
util_version.o
helio_drift.o
helio_getacch.o
helio_getacch_tp.o
helio_lindrift.o
helio_lindrift_tp.o
helio_step.o
helio_step_pl.o
helio_step_tp.o
symba3_chk.o
symba3_getacch.o
symba3_helio_drift.o
symba3_helio_getacch.o
symba3_kick.o
symba3_merge.o
symba3_nbodm.o
symba3_step_helio.o
symba3_step_interp.o
symba3_step_pl.o
symba3_step_recur_CPP.o
symba4_chk.o
symba4_getacch.o
symba4_helio_drift.o
symba4_helio_getacch.o
symba4_kick.o
symba4_merge.o
symba4_nbodm.o
symba4_step_helio.o
symba4_step_interp.o
symba4_step_pl.o
symba4_step_recur_CPP.o
symba5_chk.o
symba5_getacch.o
symba5_helio_drift.o
symba5_helio_getacch.o
symba5_kick.o
symba5_merge.o
symba5_nbodm.o
symba5_step_helio.o
symba5_step_interp.o
symba5_step_pl.o
symba5_step_recur_CPP.o
helio_drag.o
symba5d_step_helio.o
symba5d_step_interp.o
symba5d_step_pl.o
io_write_spin.o
spin_planets.o
spin_planets_enc.o
spin_planets_noenc.o
spin_sun.o
symba5s_step_helio.o
symba5s_step_interp.o
symba5s_step_pl.o
symba5s_step_recur_CPP.o
DONE
 
 
Compiling the fortran fitting routines, OK? (you must, if you haven't done it already!)
 
 
 
 
Compiling Symba/mvs and other N-body routines, OK? (you must, if you haven't done it already!)
 
 

```

With bash installers/MAC_OS_install.sh it's the same, except for `rxvt - not installed! Please install the rxvt bash shell for better experience (xterm used by default)` where instead it says yes!

**Comment by jvines** [comment]
Well, after updating to the latest version it started working for me, so no need to reopen this.

Thanks, Trifon!
