### ISSUE TITLE
If you get "Segmentation fault", please read!

### ISSUE THREAD

**Issue by 3fon3fonov** [3fon3fonov/exostriker#60]
If you experience "Segmentation fault", please start the GUI with:

` $python3.11 -m exostriker -debug`

And try to reproduce the problem. When the GUI crashes, you will see the actual error on the terminal. Then open a new issue with:

* brief description of the problem
* your OS
* your python version 
* your dependencies versions (the "-debug" flag will print this for you) 
* and the log of the error

**Comment by 3fon3fonov** [comment]
BTW, if your session was interrupted by Segmentation fault, try to recover it, by:

exostriker -ses auto_save.ses

**Comment by dmontesg** [comment]
Hi Trifon,  
I install exostriker in my Mac OS Catalina after some updates, etc. following you README_for_installation all seems to work and the GUI is open I can go to "Data inspector" select the HIRES data of HD82943 and see in the the plot bur when I click on "Load" the GUI close and running with -debug I obtain this:

> 1 Wrong data format in line 1 of fortran output, line skipped.
> 
> <class 'IndexError'> list index out of range <traceback object at 0x7fb769ee3680>
> ===== 2021.04.04 21:04:31 =====
> Traceback (most recent call last):
>   File "/opt/anaconda3/lib/python3.8/site-packages/exostriker/gui.py", line 7095, in load_data_inspect
>     self.init_fit()
>   File "/opt/anaconda3/lib/python3.8/site-packages/exostriker/gui.py", line 4529, in init_fit
>     self.update_plots()
>   File "/opt/anaconda3/lib/python3.8/site-packages/exostriker/gui.py", line 3781, in update_plots
>     self.update_RV_plots()
>   File "/opt/anaconda3/lib/python3.8/site-packages/exostriker/gui.py", line 2401, in update_RV_plots
>     error_list = self.add_jitter(fit.fit_results.rv_model.rv_err, fit.filelist.idset)
>   File "/opt/anaconda3/lib/python3.8/site-packages/exostriker/gui.py", line 4539, in add_jitter
>     errors_with_jitt = np.array([np.sqrt(errors[i]**2 + fit.params.jitters[ii]**2)  for i,ii in enumerate(ind)])
>   File "/opt/anaconda3/lib/python3.8/site-packages/exostriker/gui.py", line 4539, in <listcomp>
>     errors_with_jitt = np.array([np.sqrt(errors[i]**2 + fit.params.jitters[ii]**2)  for i,ii in enumerate(ind)])
> IndexError: list index out of range
> 
> Abort

I try with other files in the computer and the same.

When I update the python dependencies I also found this problem:

> exostriker 0.57 requires matplotlib==3.2.1, but you have matplotlib 3.4.1 which is incompatible.

I do not known if this is another problem.

The files for transits can be load without problem, but I not able to run TLS.

Regards,
David

**Comment by 3fon3fonov** [comment]
Thanks, David! This could be a bug in "load_data_inspect", which is probably not getting all data from the RVBank. I had similar problems before, but I was sure I fix them. Let me make my own test on Mac OS and will be bach to you asap. The second problem on TLS, I think comes from the tqdm package, which comes with anaconda3. See https://github.com/3fon3fonov/exostriker/issues/67 Check your versions and report the the progress in the latter "issue" thread.

**Comment by 3fon3fonov** [comment]
Actually, it is far better if you run in debug mode, e.g.:

$ gdb -ex r --args python3.11 -m exostriker

Then copy-paste the output of the crash report here to be examined.
