### ISSUE TITLE
TLS not working with Python3.8

### ISSUE THREAD

**Issue by jvines** [3fon3fonov/exostriker#67]
Hi @3fon3fonov ,

I'm trying to run TLS, but it fails with the following error

```python
Transit Least Squares TLS 1.0.25 (04 June 2020)
Creating model cache for 23 durations
Searching 1893 data points, 8422 periods from 0.602 to 25.167 days
Using all 8 CPU threads
Traceback (most recent call last):
  File "/Users/jvines/github/exostriker/exostriker/lib/worker.py", line 64, in run
    result = self.fn()
  File "/Users/jvines/github/exostriker/exostriker/gui.py", line 4722, in <lambda>
    worker_tls_ = Worker(lambda:  self.tls_search(resid = resid) )# Any other args, kwargs are passed to the run
  File "/Users/jvines/github/exostriker/exostriker/gui.py", line 4760, in tls_search
    tls_results = tls_model.power(period_min = tls_period_min, period_max=tls_period_max,
  File "/Users/jvines/anaconda3/envs/exostriker/lib/python3.8/site-packages/transitleastsquares/main.py", line 117, in power
    pbar = tqdm(total=numpy.size(periods), smoothing=0.3, bar_format=bar_format)
  File "/Users/jvines/anaconda3/envs/exostriker/lib/python3.8/site-packages/tqdm/std.py", line 561, in __new__
    with cls.get_lock():  # also constructs lock if non-existent
  File "/Users/jvines/anaconda3/envs/exostriker/lib/python3.8/site-packages/tqdm/std.py", line 660, in get_lock
    cls._lock = TqdmDefaultWriteLock()
  File "/Users/jvines/anaconda3/envs/exostriker/lib/python3.8/site-packages/tqdm/std.py", line 98, in __init__
    cls.create_mp_lock()
  File "/Users/jvines/anaconda3/envs/exostriker/lib/python3.8/site-packages/tqdm/std.py", line 122, in create_mp_lock
    cls.mp_lock = RLock()
  File "/Users/jvines/anaconda3/envs/exostriker/lib/python3.8/multiprocessing/context.py", line 73, in RLock
    return RLock(ctx=self.get_context())
  File "/Users/jvines/anaconda3/envs/exostriker/lib/python3.8/multiprocessing/synchronize.py", line 187, in __init__
    SemLock.__init__(self, RECURSIVE_MUTEX, 1, 1, ctx=ctx)
  File "/Users/jvines/anaconda3/envs/exostriker/lib/python3.8/multiprocessing/synchronize.py", line 80, in __init__
    register(self._semlock.name, "semaphore")
  File "/Users/jvines/anaconda3/envs/exostriker/lib/python3.8/multiprocessing/resource_tracker.py", line 147, in register
    self._send('REGISTER', name, rtype)
  File "/Users/jvines/anaconda3/envs/exostriker/lib/python3.8/multiprocessing/resource_tracker.py", line 154, in _send
    self.ensure_running()
  File "/Users/jvines/anaconda3/envs/exostriker/lib/python3.8/multiprocessing/resource_tracker.py", line 121, in ensure_running
    pid = util.spawnv_passfds(exe, args, fds_to_pass)
  File "/Users/jvines/anaconda3/envs/exostriker/lib/python3.8/multiprocessing/util.py", line 452, in spawnv_passfds
    return _posixsubprocess.fork_exec(
ValueError: bad value(s) in fds_to_keep
```

I suspect it might be a python 3.8 thing since it changed how multiprocessing works. They switched from fork to spawn which broke a lot of things.

**Comment by jvines** [comment]
As a follow-up. Reverting to Python 3.7 fixed the issue

**Comment by 3fon3fonov** [comment]
Interesting... I am running python3.8 all the time and I never experienced this problem. 

Perhaps is also anaconda3 repated? Update tqdm.

when I find time I will try to reproduce your problem. Which MAC OS you are running?

**Comment by 3fon3fonov** [comment]
I just verified, TLS within the Exo-Striker works perfectly fine on Python3.8 and Linux.

please run:


$ python3.8 exostriker_gui.py -debug

and check your transitleastsquares version (you may also paste the whole output for inspection).

Mine is:

transitleastsquares==1.0.24

and tqdm 

tqdm==4.48.2

**Comment by jvines** [comment]
I'm running OS X Catalina.

I'll create a new environment to reproduce the error and update here

**Comment by 3fon3fonov** [comment]
Any progress on this? Or it was permanently solved?

**Comment by 3fon3fonov** [comment]
I suppose this was already fixed. Please re-open if needed.
