### ISSUE TITLE
module 'os' has no attribute 'setsid'

### ISSUE THREAD

**Issue by sai-33** [3fon3fonov/exostriker#73]
Installing the swift N-body lib for a first time!
<class 'AttributeError'> module 'os' has no attribute 'setsid' <traceback object at 0x000001CD4FD5F380>
===== 2021.05.31 12:05:08 =====
Traceback (most recent call last):
  File "C:\Users\hp\Desktop\exostriker\exostriker_gui.py", line 3, in <module>
    exostriker.gui.main()
  File "C:\Users\hp\Desktop\exostriker\exostriker\gui.py", line 9470, in main
    window = Exo_striker()
  File "C:\Users\hp\Desktop\exostriker\exostriker\gui.py", line 8614, in __init__
    self.check_fortran_routines()
  File "C:\Users\hp\Desktop\exostriker\exostriker\gui.py", line 7943, in check_fortran_routines
    result6, flag6 = rv.run_command_with_timeout('./install_swift.sh', 600,output=True)
  File "C:\Users\hp\Desktop\exostriker\exostriker\lib\RV_mod\functions.py", line 1995, in run_command_with_timeout
    proc = Popen(args, shell=True, preexec_fn=os.setsid, stdout=text, stderr=text)
AttributeError: module 'os' has no attribute 'setsid'

**Comment by sai-33** [comment]
Can you make an installation video? Please

**Comment by 3fon3fonov** [comment]
Are you trying to install the Exo-Striker on a Windows10 python environment?  "setsid" is not available on Windows. I would recommend installing the Linux Kernel on Win10 and install the tool there. See instructions here under Windows10: https://github.com/3fon3fonov/exostriker/blob/exostriker-ready/README_for_installation
