### ISSUE TITLE
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.

### ISSUE THREAD

**Issue by 3fon3fonov** [3fon3fonov/exostriker#98]
I have seen this "bug" in Linux/Ubuntu machines, but is probably not limited to Ubuntu/

```
$ python3.8 exostriker_gui.py

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even
though it was found.
This application failed to start because no Qt platform plugin could be
initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl,
offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl,
wayland-xcomposite-glx, webgl, xcb.
```

The fix was found on the internet, but I have not spent much time to understand the error. 

`sudo apt install libxkbcommon-x11-0`

or

`sudo apt install libxcb-xinerama0`

Obviously, there is some missing X11 libraries in fresh Ubuntu install.

**Comment by 3fon3fonov** [comment]
Please let me know if you have encountered this problem and if the above solutions have worked out.

**Comment by danirevi** [comment]
Hi,

I don't really know if my problem has relation to this, but I let you know it because it has to do with Qt although it might only be coincidence.

When installing exostriker I get the following error:
`aise Exception('pyqtgraph requires Qt version >= %d.%d  (your version is %s)' % (versionReq[0], versionReq[1], QtVersion))
Exception: pyqtgraph requires Qt version >= 5.12  (your version is 5.9.6)`

I haven't found any way to solve this, nor to upgrade Qt version.
Thanks

**Comment by 3fon3fonov** [comment]
Hello @danirevi,

I think your problem is different. Obviously, your PyQt5 is too old for the new version of pyqtgraph, which runs the interactive plots. 

perhaps try to upgrade your PyQt5. Exo-Striker by default requires PyQt5>=5.15.4. Try:

$ pip3 install PyQt5==5.15.4 

or 

$ pip3 install PyQt5 -U

You may need sudo in from of pip3, assuming pip3 is tied to your Python3.7 + installation. 

If you are unsure, inspect the setup.py file in the root github directory and the installation tips in the README.md.

If you still have difficulties, please open another (separate) issue and I will assist.

**Comment by schaubia** [comment]
Hi,

Installing the package libxcb-xinerama0:
$ sudo apt-get install libxcb-xinerama0
solved the problem for me.

My current distribution:
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"

Note that using the git clone installation, I had to manually install all necessary packages listed in the README for installation file.

**Comment by 3fon3fonov** [comment]
I have been just reported that the above fixes did not work on Win10 with WLS2 with installed Ubuntu 20.04 app. However, the following did the trick:

$ sudo apt-get install qt5-default

**Comment by schaubia** [comment]
Hi, I have WSL with Ubuntu 22.04, and unfortunately, after Ubuntu 21.0 qt5-default package is no longer in the Ubuntu repo. I've found a solution to try in the following thread:

https://askubuntu.com/questions/1335184/qt5-default-not-in-ubuntu-21-04

and tried to install all packages; however, I receive the following error:

Traceback (most recent call last):
  File "/home/schaubia/exostriker/exostriker_gui.py", line 3, in <module>
    exostriker.gui.main()
  File "/home/schaubia/exostriker/exostriker/gui.py", line 11699, in main
    window = Exo_striker()
  File "/home/schaubia/exostriker/exostriker/gui.py", line 10959, in __init__
    self.calculator = calc.Calculator()
  File "/home/schaubia/exostriker/exostriker/lib/calculator.py", line 156, in __init__
    mainLayout.addWidget(self.digitButtons[i], row, column)
TypeError: arguments did not match any overloaded call:
  addWidget(self, QWidget): too many arguments
  addWidget(self, QWidget, int, int, alignment: Union[Qt.Alignment, Qt.AlignmentFlag] = Qt.Alignment()): argument 2 has unexpected type 'float'
  addWidget(self, QWidget, int, int, int, int, alignment: Union[Qt.Alignment, Qt.AlignmentFlag] = Qt.Alignment()): argument 2 has unexpected type 'float'

Aborted (core dumped)

**Comment by schaubia** [comment]
Hi, I have WSL with Ubuntu 22.04, and unfortunately, after Ubuntu 21.0 qt5-default package is no longer in the Ubuntu repo. I've found a solution to try in the following thread:

https://askubuntu.com/questions/1335184/qt5-default-not-in-ubuntu-21-04

and tried to install all packages; however, I receive the following error:

Traceback (most recent call last):
  File "/home/schaubia/exostriker/exostriker_gui.py", line 3, in <module>
    exostriker.gui.main()
  File "/home/schaubia/exostriker/exostriker/gui.py", line 11699, in main
    window = Exo_striker()
  File "/home/schaubia/exostriker/exostriker/gui.py", line 10959, in __init__
    self.calculator = calc.Calculator()
  File "/home/schaubia/exostriker/exostriker/lib/calculator.py", line 156, in __init__
    mainLayout.addWidget(self.digitButtons[i], row, column)
TypeError: arguments did not match any overloaded call:
  addWidget(self, QWidget): too many arguments
  addWidget(self, QWidget, int, int, alignment: Union[Qt.Alignment, Qt.AlignmentFlag] = Qt.Alignment()): argument 2 has unexpected type 'float'
  addWidget(self, QWidget, int, int, int, int, alignment: Union[Qt.Alignment, Qt.AlignmentFlag] = Qt.Alignment()): argument 2 has unexpected type 'float'

Aborted (core dumped)

**Comment by 3fon3fonov** [comment]
Hi @schaubia, can you please report which python3 and which PyQt5 version you are using?

**Comment by schaubia** [comment]
Hi, I have Python 3.10.4 and PyQt5-5.15.6 .

**Comment by 3fon3fonov** [comment]
Now the above solutions do not work on Python3.10+ and PyQt6 and Ubuntu 22.04. Yet, so far I have seen the problem only in one machine. When solution is found will be posted here.

**Comment by 3fon3fonov** [comment]
This is way too old issue, not relevant to the new Exo-Striker (0.94.2 + ) so I am closing.
